# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KinematicsZebra.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KinematicsZebra(object):
    def setupUi(self, KinematicsZebra):
        KinematicsZebra.setObjectName("KinematicsZebra")
        KinematicsZebra.resize(580, 222)
        KinematicsZebra.setMinimumSize(QtCore.QSize(580, 222))
        KinematicsZebra.setMaximumSize(QtCore.QSize(580, 222))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/gar-fish.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        KinematicsZebra.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(KinematicsZebra)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 501, 134))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vidPathLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.vidPathLineEdit.setObjectName("vidPathLineEdit")
        self.gridLayout.addWidget(self.vidPathLineEdit, 0, 1, 1, 4)
        self.vidPathLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.vidPathLabel.setObjectName("vidPathLabel")
        self.gridLayout.addWidget(self.vidPathLabel, 0, 0, 1, 1)
        self.savePathLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.savePathLabel.setObjectName("savePathLabel")
        self.gridLayout.addWidget(self.savePathLabel, 2, 0, 1, 1)
        self.expIDLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.expIDLabel.setObjectName("expIDLabel")
        self.gridLayout.addWidget(self.expIDLabel, 1, 0, 1, 1)
        self.savePathLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.savePathLineEdit.setObjectName("savePathLineEdit")
        self.gridLayout.addWidget(self.savePathLineEdit, 2, 1, 1, 4)
        self.expIDLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.expIDLineEdit.setStyleSheet("color: grey;\n"
"")
        self.expIDLineEdit.setText("")
        self.expIDLineEdit.setReadOnly(True)
        self.expIDLineEdit.setPlaceholderText("")
        self.expIDLineEdit.setObjectName("expIDLineEdit")
        self.gridLayout.addWidget(self.expIDLineEdit, 1, 1, 1, 1)
        self.vidPathTButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.vidPathTButton.setObjectName("vidPathTButton")
        self.gridLayout.addWidget(self.vidPathTButton, 0, 5, 1, 1)
        self.savePathTButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.savePathTButton.setObjectName("savePathTButton")
        self.gridLayout.addWidget(self.savePathTButton, 2, 5, 1, 1)
        self.fpsSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.fpsSpinBox.setMinimum(1)
        self.fpsSpinBox.setMaximum(2000)
        self.fpsSpinBox.setProperty("value", 1000)
        self.fpsSpinBox.setObjectName("fpsSpinBox")
        self.gridLayout.addWidget(self.fpsSpinBox, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.fpsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.fpsLabel.setObjectName("fpsLabel")
        self.gridLayout.addWidget(self.fpsLabel, 1, 3, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 180, 521, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setAcceptDrops(False)
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(10)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.progressLabel = QtWidgets.QLabel(self.layoutWidget)
        self.progressLabel.setEnabled(True)
        self.progressLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.progressLabel.setAutoFillBackground(False)
        self.progressLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.progressLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.progressLabel.setObjectName("progressLabel")
        self.horizontalLayout.addWidget(self.progressLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.RunButton = QtWidgets.QPushButton(self.layoutWidget)
        self.RunButton.setEnabled(True)
        self.RunButton.setCheckable(False)
        self.RunButton.setAutoDefault(False)
        self.RunButton.setDefault(False)
        self.RunButton.setFlat(False)
        self.RunButton.setObjectName("RunButton")
        self.horizontalLayout.addWidget(self.RunButton)
        KinematicsZebra.setCentralWidget(self.centralwidget)

        self.retranslateUi(KinematicsZebra)
        QtCore.QMetaObject.connectSlotsByName(KinematicsZebra)

    def retranslateUi(self, KinematicsZebra):
        _translate = QtCore.QCoreApplication.translate
        KinematicsZebra.setWindowTitle(_translate("KinematicsZebra", "Kinematics Zebra"))
        self.vidPathLineEdit.setPlaceholderText(_translate("KinematicsZebra", "Select a video..."))
        self.vidPathLabel.setText(_translate("KinematicsZebra", "Video Path:"))
        self.savePathLabel.setText(_translate("KinematicsZebra", "Save Path:"))
        self.expIDLabel.setText(_translate("KinematicsZebra", "Exp. ID:"))
        self.savePathLineEdit.setPlaceholderText(_translate("KinematicsZebra", "Select a path..."))
        self.vidPathTButton.setText(_translate("KinematicsZebra", "..."))
        self.savePathTButton.setText(_translate("KinematicsZebra", "..."))
        self.fpsLabel.setText(_translate("KinematicsZebra", "fps:"))
        self.progressLabel.setText(_translate("KinematicsZebra", "Ready"))
        self.RunButton.setText(_translate("KinematicsZebra", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KinematicsZebra = QtWidgets.QMainWindow()
    ui = Ui_KinematicsZebra()
    ui.setupUi(KinematicsZebra)
    KinematicsZebra.show()
    sys.exit(app.exec_())

